### ISSUE TITLE
Linux using openjdk requires openjfx

### ISSUE THREAD

**Issue by rebeccaloran** [SMerrony/EWItool#14]
Running the jar file without it installed results in an error:

`$ java -version`
`openjdk version "1.8.0_144"`
`OpenJDK Runtime Environment (build 1.8.0_144-b01)`
`OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
`

`$ java -jar ewitool.jar `
`Error: Could not find or load main class ewitool.Main
`

Program seems to be running fine after installing java-openjfx-8.u172-1-x86_64 on Archlinux

**Comment by SMerrony** [comment]
Thanks - I was aware of that, but forgot to document it for using EWItool with OpenJDK.  Will update the docs this week.

**Comment by SMerrony** [comment]
Fixed by updating wiki using/installing page.
