### ISSUE TITLE
Fetching EWI patches

### ISSUE THREAD

**Issue by WlodzislawD** [SMerrony/EWItool#15]
Fetching EWI 4000s patches via Roland Cakewalk UM-2G USB-Midi interface stops after 88 patches have been loaded. I have tried to change driver (Win 10 automatically loads the uM-2G driver) and use different USB sockets, but no luck ... 
Win 10-64 Home, Java 8-151, EWI with Patchmen sounds.
A pity because EWItool seems to be an interesting software, thank you for creating it. 
Some new presets worth loading are now available. 

Wlodzislaw

**Comment by WlodzislawD** [comment]
Somehow patch 88 got damadged withing the EWI. 
Reloading original patches from Patchmen solved the problem.
Regards, Wlodizslaw

**Comment by SMerrony** [comment]
Do you think that EWItool damaged the patch?
The only time I have seen this happen is if the batteries fail (or the EWI is turned off) in the middle of uploading patches.

**Comment by SMerrony** [comment]
Closing this for now.
