### ISSUE TITLE
Cannot build without Oracle JDK

### ISSUE THREAD

**Issue by admiyo** [SMerrony/EWItool#3]
I'm sure there are strong reasons for switch from C++ to Java, but getting the Java library necessary to build this has proven to be painful.  The best I saw was OpenJFX, but even that said said "in order to download the JFX binary you need to be a member of OTN."

**Comment by SMerrony** [comment]
If you are using OpenJDK: as the OpenJDK maintainers have not yet rolled the (now open-source) FX stuff into the toolkit you will need to install the openjfx package which is available in various repos.  (You don't need this to execute the distributed jar versions of EWItool.)
