### ISSUE TITLE
USB connection on Linux

### ISSUE THREAD

**Issue by admiyo** [SMerrony/EWItool#6]
I'm running Fedora 23. 
Selecting  USB ports seems to work, but I do see the WARNING:

Warning - Unrecognised SysEx type of length 34 received from EWI, starting: 126 5 6

Attempting to Fetch all  patches gives the error: Not connected to EWI40001s

I'm running with an AKAI EWIUSB.  Qsynth and QJackCtrl seem to work OK with the device.

I'm, using the Oracle JDK version 

$ ~/apps/jdk/jdk1.8.0_74/bin/java  -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

And the downloaded Jar file run like this:

~/apps/jdk/jdk1.8.0_74/bin/java  -jar ~/Downloads/EWItool_1_95.jar

**Comment by admiyo** [comment]
The first few bytes of the message are:
-16 126 5 6 2 71 109 0 25 0 1

**Comment by admiyo** [comment]
In MidiReceiver, I see that the 126 value maps to:

but then the second value is 5, not 0, which the comment indicates is the device ID.  Could that be the channel?  I did change the channel using the Windows based program that ships with the EWI to 5, but I would not expect this to break here.

After that, it fails on 

if (messageBytes.length != (MidiHandler.EWI_SYSEX_ID_RESPONSE_LEN - 1)) {
            sharedData.deviceIdQ.add( SharedData.DeviceIdResponse.WRONG_LENGTH );
            return;
          }

as this message is 34 bytes long, not 14.

I suspect this is due to the the difference in models for the EWIs.

**Comment by SMerrony** [comment]
As stated all over the documentation: EWItool only supports the EWI4000s - not any other type whatsoever.
