### ISSUE TITLE
Can't see all the patches on the screen in Win7 - 1280x768, medium fonts (125%)

### ISSUE THREAD

**Issue by Andy2No** [SMerrony/EWItool#7]
(Sorry; I can't see how to edit the title - that should say 1360x768)

Using a 1360x768 LCD TV as my monitor, in Windows 7 SP1 x64, with "medium" fonts (125% size), I only see the first 18 patches in each column, in the patch set, using EWItool 2.0, whether or not I make it full screen.  

There is no scroll bar, so there doesn't appear to be any way of seeing the rest, on this display, other than changing to uncomfortably small fonts.

**Comment by Andy2No** [comment]
![patch set truncated in 2 0](https://cloud.githubusercontent.com/assets/8021302/17374671/9d011f6a-59a5-11e6-9d23-dfcf678c3a78.gif)

**Comment by Andy2No** [comment]
This also appears to stop me saving the entire patch set to the Patch Library, because I can't see the button, which the help information refers to, that's meant to be at the bottom of the tab.  

I don't see any way of doing that through the menus, so it would seem the missing button was the only way of doing it.

**Comment by Andy2No** [comment]
I did find a work around to this, which involved recompiling from the sources with an altered style sheet, removing the vertical spacing between patch names in the current patch set - which was more than a bit daunting, since I had to work out how to compile it.   See Issue #8 for the feature request to read in the style sheet on loading the program.

That also allowed me to see and get to the **Save To Library** button, when viewing ewitool 2.00 in a window, and to see some other information at the bottom of the screen when in full screen mode - though not both at the same time.  I could probably improve on that, by tweaking the style sheet a bit more, but it's working well enough, for now.

Here are a couple of screen shots, after reducing the vertical spacing, like this:

#current-patch-set-grid {
    -fx-padding: 1mm;
    -fx-hgap: 2mm;
    -fx-vgap: 1mm; /* change to 0mm */

}

In a window - I can now see all patches and use the button to save the patch set to a file:

![current-patch-set-grid fx-vgap 0 window on 1360x768](https://cloud.githubusercontent.com/assets/8021302/20540359/de708f2e-b0f0-11e6-9934-1bb2f3b50694.gif)

Full screen - I can see the selected MIDI channels etc, though not the **Save To Library** button:

![current-patch-set-grid fx-vgap 0 full screen on 1360x768](https://cloud.githubusercontent.com/assets/8021302/20540360/de75863c-b0f0-11e6-90ab-827f5b8dfe8d.gif)

**Comment by SMerrony** [comment]
Closing this for now as I have implemented #8 for release 2.1 and documented how to use your own CSS in the wiki at [Customising (or 'skinning') EWItool](https://github.com/SMerrony/EWItool/wiki/Customising-(or-'skinning')-EWItool).
