### ISSUE TITLE
Feature request - optionally load a user defined style sheet

### ISSUE THREAD

**Issue by Andy2No** [SMerrony/EWItool#8]
I mentioned a problem, in an earlier issue ( issue #7 ), with getting enough of the patch list on the screen, on a 1360x768 LCD monitor / TV, in Windows 7, with medium fonts.

It turned out the work around was to recompile, after making a very small change to the style sheet, reducing a vertical spacing.  There was quite a learning curve involed in doing that the first time, of course, so most people probably wouldn't attempt it.

As discussed, please implement reading in a user defined style sheet, if one is present - e.g, in the same directory / folder that ewitool is launched from.

It would probably be best to supply the style sheet as part of the standard installation, so people didn't have to look for it in the sources.

**Comment by SMerrony** [comment]
Good idea.  Will implement a user CSS in version 2.1

**Comment by SMerrony** [comment]
Done for version 2.1
If a file called "user.css" exists in the EWItool Libary Location then it will be loaded after the default stylesheet.
